% u = [del_s; del_b]
U_cstr = [eye(2); -eye(2)];
U_cstr_b = 0.25*ones(4,1);

% x = [     z_dot;  theta_dot;  theta;  z]
X_cstr = [  0       0           1       0;...
            0       0           -1      0;...
            ...
            0       10          1       0;...
            0       10          -1      0;...
            0       -10         1       0;...
            0       -10         -1      0;...
            ...
            1       0           0       0;...
            -1      0           0       0;...
            ...
            0       0           0       1;...
            0       0           0       -1];

X_cstr_b = [0.25;0.25;...
            0.5;0.5;-0.5;-0.5;...
            0.4;0.4;...
            50;50];
        
% x = [     z_dot;  theta_dot;  theta;  z]
Xf_cstr = [ 0       0           0       1;...
            0       0           0       -1;...
            ...
            1       0           0       0;...
            -1      0           0       0;...
            ...
            0       0           1       0;...
            0       0           -1      0;...
            ...
            0       1           0       0;...
            0       -1          0       0];

Xf_cstr_b=[ 0.2;0.2;...
            0.1;0.1;...
            0.02;0.02;...
            0.005;0.005];
        
%% Create monstermatrices

load System.mat


cstr.U_cstr = repmat(U_cstr, 1, dim.N);
cstr.U_cstr_b = repmat(U_cstr_b, 1, dim.N);
cstr.X_cstr = repmat(X_cstr, 1, dim.N);
cstr.X_cstr_b = repmat(X_cstr_b, 1, dim.N);
cstr.Xf_cstr = Xf_cstr;
cstr.Xf_cstr_b = Xf_cstr_b;

save cstrMat.mat cstr

