% u = [del_s; del_b]
U_cstr = [eye(2); -eye(2)];
U_cstr_b = 15*ones(4,1);%0.25*ones(4,1);

% x = [     z_dot;  theta_dot;  theta;  z]
X_cstr = [  0       0           1       0;...
            0       0           -1      0;...
            ...
            0       10          1       0;...
            0       10          -1      0;...
            0       -10         1       0;...
            0       -10         -1      0;...
            ...
            1       0           0       0;...
            -1      0           0       0;...
            ...
            0       0           0       1;...
            0       0           0       -1];

X_cstr_b = [15;15;... 0.25;0.25;...
            5;5;5;5;...0.5;0.5;0.5;0.5;...
            3;3;...
            10;10];
        
% x = [     z_dot;  theta_dot;  theta;  z]
Xf_cstr = [ 0       0           0       1;...
            0       0           0       -1;...
            ...
            1       0           0       0;...
            -1      0           0       0;...
            ...
            0       0           1       0;...
            0       0           -1      0;...
            ...
            0       1           0       0;...
            0       -1          0       0];

Xf_cstr_b=[ 0.01;0.01;...
            0.1;0.1;...
            0.15;0.15;...
            0.05;0.05];
        
%% Create monstermatrices

load System.mat


cstr.U_cstr = kron(eye(dim.N), U_cstr);
cstr.U_cstr_b = repmat(U_cstr_b, dim.N, 1);
cstr.X_cstr = kron(eye(dim.N+1), X_cstr);
cstr.X_cstr_b = repmat(X_cstr_b, dim.N+1, 1);
cstr.U_cstr1 = U_cstr;
cstr.U_cstr_b1 = U_cstr_b;
cstr.X_cstr1 = X_cstr;
cstr.X_cstr_b1 = X_cstr_b;
cstr.Xf_cstr = Xf_cstr;
cstr.Xf_cstr_b = Xf_cstr_b;



save cstrMat.mat cstr

